name: Test 
on: [push]
jobs:
  test-phpunit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: nick-zh/composer@php7.4
      - name: run tests 
        run: make test 